// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIE1opIZn-1MhhngjZat8x9I2UifKz4Qo',
    appId: '1:691506639052:android:e05f1ccf04b7e7933cd269',
    messagingSenderId: '691506639052',
    projectId: 'ar-base-plant-flutter',
    databaseURL: 'https://ar-base-plant-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'ar-base-plant-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8cRwJsRhAa5UUykFByOJA4xEot2c2Y9w',
    appId: '1:691506639052:ios:27e3b5e48d68f5973cd269',
    messagingSenderId: '691506639052',
    projectId: 'ar-base-plant-flutter',
    databaseURL: 'https://ar-base-plant-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'ar-base-plant-flutter.appspot.com',
    iosClientId: '691506639052-08eq66i21epinmif3qd1t937hjatcqqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.arBasePlantApp',
  );

}